// Runtime-local assets: Metro resolves these static require calls into the app bundle.
// The cuisine cover art is original flat-illustration work generated by
// `scripts/demo-art/build-art.mjs`. `coverFor()` chooses an appetizing cover for a
// restaurant/drop: first by matching cuisine keywords in the restaurant name (so a
// biryani place shows the biryani cover), else by a stable name hash. It is keyed
// on the restaurant name, which both the drop and restaurant DTOs carry, so the
// same restaurant shows the same cover everywhere. Real uploaded media still takes
// priority via ProductMedia's `media` prop; the keyword vocabulary is generic
// (not demo-hardcoded).
const covers = {
  biryani: require("../../assets/art/cover-biryani.png"),
  thali: require("../../assets/art/cover-thali.png"),
  grill: require("../../assets/art/cover-grill.png"),
  coastal: require("../../assets/art/cover-coastal.png"),
  bakery: require("../../assets/art/cover-bakery.png"),
} as const;

type CoverKey = keyof typeof covers;
const coverOrder = Object.keys(covers) as CoverKey[];

// First match wins; ordered so the strongest signal is checked before generic ones.
const cuisineKeywords: readonly (readonly [RegExp, CoverKey])[] = [
  [/biryani|hyderabad|dum\b|pulao|mughlai|nawab|handi/i, "biryani"],
  [/grill|smoky|tandoor|kebab|bbq|barbe|charcoal|north.?indian|continental/i, "grill"],
  [/andhra|coastal|seafood|\bfish\b|chettinad|malabar|spice trail/i, "coastal"],
  [/bakery|baker|sweet|cake|dessert|patisser|choco|bread|bake\b/i, "bakery"],
  [/sattvi|thali|south.?indian|\bveg\b|jain|pure.?veg|multi.?cuisine|tiffin/i, "thali"],
];

function hashIndex(key: string, modulo: number): number {
  let hash = 0;
  for (const character of key.normalize("NFC")) hash = (hash * 31 + character.codePointAt(0)!) >>> 0;
  return hash % modulo;
}

/** Appetizing cover for a restaurant/drop: cuisine-accurate by name, else stable hash. */
export function coverFor(key: string | null | undefined) {
  const safe = (key ?? "").trim();
  if (!safe) return covers.biryani;
  for (const [pattern, cover] of cuisineKeywords) {
    if (pattern.test(safe)) return covers[cover];
  }
  return covers[coverOrder[hashIndex(safe, coverOrder.length)] ?? "biryani"];
}

export const mediaFallbacks = {
  // Back-compat defaults for any call site without a key.
  drop: covers.biryani,
  restaurantCover: covers.thali,
  coverFor,
} as const;
