// Runtime-local assets: Metro resolves these static require calls into the app bundle.
// The cuisine cover art is original flat-illustration work generated by
// `scripts/demo-art/build-art.mjs`. `coverFor()` chooses an appetizing cover for a
// restaurant/drop: first by cuisine keyword (shared `cuisineCoverKey` from
// @gozaika/utils, so mobile and web agree), else by a stable name hash. It is keyed
// on the restaurant name, which both the drop and restaurant DTOs carry, so the
// same restaurant shows the same cover everywhere. Real uploaded media still takes
// priority via ProductMedia's `media` prop.
import { COVER_KEYS, cuisineCoverKey, dropCoverKey, type CoverKey } from "@gozaika/utils";

const covers: Record<CoverKey, number> = {
  biryani: require("../../assets/art/cover-biryani.jpg"),
  thali: require("../../assets/art/cover-thali.jpg"),
  grill: require("../../assets/art/cover-grill.jpg"),
  coastal: require("../../assets/art/cover-coastal.jpg"),
  bakery: require("../../assets/art/cover-bakery.jpg"),
};

// Cuisine-agnostic cover for blind-bag drops (must not reveal the cuisine).
const mysteryCover: number = require("../../assets/art/cover-mystery.png");

function hashIndex(key: string, modulo: number): number {
  let hash = 0;
  for (const character of key.normalize("NFC")) hash = (hash * 31 + character.codePointAt(0)!) >>> 0;
  return hash % modulo;
}

/** Appetizing cover for a restaurant/drop: cuisine-accurate by name, else stable hash. */
export function coverFor(key: string | null | undefined) {
  const safe = (key ?? "").trim();
  if (!safe) return covers.biryani;
  const matched = cuisineCoverKey(safe);
  if (matched) return covers[matched];
  return covers[COVER_KEYS[hashIndex(safe, COVER_KEYS.length)] ?? "biryani"];
}

/**
 * Cover for a drop. Blind-bag drops show the cuisine-agnostic mystery cover (so
 * the cuisine stays hidden until pickup); everything else uses `coverFor`. Keyed
 * on the restaurant name so a restaurant's non-blind drops match its profile cover.
 */
export function coverForDrop(drop: { restaurantName?: string | null; dropTypeCode?: string | null }) {
  if (dropCoverKey(drop) === "mystery") return mysteryCover;
  return coverFor(drop.restaurantName);
}

export const mediaFallbacks = {
  // Back-compat defaults for any call site without a key.
  drop: covers.biryani,
  restaurantCover: covers.thali,
  coverFor,
  coverForDrop,
} as const;
